spring:
  application:
    name: spring-ai-ollama
  ai:
    model:
      chat: ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: phi3:mini
          temperature: 0.7

